import Link from "next/link";

export default function GeneralTermsPage() {
    return (

        <div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 flex gap-4 flex-col">
            <h1 className="mb-2 text-2xl font-bold text-zinc-900 dark:text-white">General Terms and Conditions of Sale for Non-Commercial Transactions (Buyer is a Consumer)</h1>
            <hr className="w-full text-gray-200" />
            <div className="w-full flex flex-col gap-4 items-start py-4">
                <h2 className="text-lg font-semibold">§ 1 Scope</h2>
                <p>1.1 These General Terms and Conditions (hereinafter referred to as “T&Cs”) of Sound Service GmbH (hereinafter referred to as “Seller”) apply to all contracts for the delivery of goods concluded by a consumer (hereinafter referred to as “Customer”) with the Seller with regard to the goods presented by the Seller in its online shop. Unless otherwise agreed, the inclusion of the Customer’s own terms and conditions is hereby rejected.</p>
                <p>1.2 A consumer within the meaning of these T&Cs is any natural person who enters into a legal transaction for purposes that are for the most part not attributable to his or her commercial or self-employed professional activity.</p>

                <h2 className="text-lg font-semibold">§ 2 Conclusion of contract</h2>
                <p>2.1 The product descriptions contained in the Seller’s online shop and catalogue do not constitute binding offers on the part of the Seller, but are used for the submission of a binding offer by the Customer. The same applies to our offers on flyers, in newsletters or in advertisements, which are always non-binding and subject to change.</p>
                <p>2.2 Sound Service reserves the right not to supply the promised goods or services if it becomes apparent after conclusion of the contract that the goods are not available even though a corresponding binding transaction has been concluded. In such a case, the Customer will be notified immediately. Any amounts already paid will be refunded immediately. Any further claims against Sound Service are excluded.</p>
                <p>2.3 The Customer may submit the Offer via the online order form integrated into the Seller’s online shop. After placing the selected goods in the virtual shopping basket and going through the electronic ordering process, the Customer submits a legally binding offer to enter into a contract with respect to the goods contained in the shopping basket by clicking the button to conclude the ordering process. The Customer may also submit the offer to the Seller by telephone, fax, email or post.</p>
                <p>2.4 The Seller may accept the Customer’s offer within fourteen days,</p>
                <ul>
                    <li>by sending the Customer a written order confirmation or other order confirmation in text form (fax or email), in which case the receipt of the order confirmation by the Customer will be decisive, or</li>
                    <li>by delivering the ordered goods to the Customer, in which case the receipt of the goods by the Customer will be decisive, or</li>
                    <li>by requesting payment from the Customer after the Customer has placed the order.</li>
                </ul>
                <p>If several of the aforementioned options occur, the contract will be concluded at the moment when the first of the aforementioned options occurs. The deadline for accepting the offer begins on the day after the Customer submits the offer and ends after the fifth day following submission of the offer. If the Seller does not accept the Customer’s offer within the aforementioned period, this will be deemed to be a rejection of the offer with the consequence that the Customer is no longer bound by his or her declaration of intent.<br/>The email automatically generated following the purchaser’s order, which confirms receipt of the order, does not constitute acceptance of the contract, but merely serves to fulfil the obligations pursuant to Section 312e (1) number 3 of the German Civil Code (BGB). If we accept the offer on modified terms, e.g. at a different price, this acceptance will be deemed to be an offer to conclude a modified contract (Section 150 (2) BGB). We will inform the purchaser of the modified offer in text form immediately after the order. In this case, the purchaser has the option of accepting the offer within 14 days, either explicitly or implicitly – for example by accepting the goods without objection or by email. In this respect, we dispense with the need to receive a declaration of acceptance from the purchaser (Section 151 BGB).</p>
                <p>2.5 When submitting an offer via the Seller’s online order form, the text of the contract will be stored by the Seller and sent to the Customer in text form (e.g. email, fax or letter) together with these T&amp;Cs after the Customer has sent his or her order. In addition, the text of the contract is archived on the Seller’s website and can be accessed free of charge by the Customer via his or her password-protected customer account by entering the relevant login data, provided that the Customer has created a customer account on the Seller’s online shop before submitting his or her order.</p>
                <p>2.6 Order processing and contact usually take place via email and automated order processing. The Customer must ensure that the email address he or she provides for the order processing is correct so that emails sent by the Seller can be received at this address. In particular, when using spam filters, the Customer must ensure that all emails sent by the Seller or by third parties commissioned by the Seller to process the order can be delivered.</p>
                <h2 className="text-lg font-semibold">§ 3 Statutory right of withdrawal</h2>
                <p>3.1 Cancellation policy for goods</p>
                <p>3.1.1 Right of withdrawal</p>
                <p>If the Customer is a consumer (Section 13 BGB), he or she has the right to withdraw from this contract without stating the reason. In the case of contracts for the delivery of goods, the withdrawal period is 14 days from the day on which you or a third party named by you, who is not the carrier, took possession of the last goods.<br/>To exercise your right of withdrawal, you must inform us (Sound Service GmbH, Moriz-Seeler-Strasse 3, 12489 Berlin, Germany, Tel: +49 (0) 30 707 130-0, email: <a href="mailto:info@zoom-europe.com">info@zoom-europe.com</a>) of your decision to withdraw from this contract by means of a clear declaration (e.g. a letter sent by post, fax or email). You can use the enclosed <a href="http://media.sound-service.eu/zoom/Zoom_Muster_WiderrufEN.pdf">sample withdrawal</a> form for this purpose, although this is not mandatory.<br /></p>
                <p>To comply with the withdrawal period, all that is required is that you send the notification exercising your right of withdrawal before the end of the withdrawal period.</p>
                <p>3.1.2 Consequences of withdrawal</p>
                <p>If you withdraw from this contract, we must refund all payments we have received from you, including delivery costs (with the exception of additional costs resulting from the fact that you have chosen a type of delivery other than the cheapest standard delivery offered by us), without delay and no later than within fourteen days of the day on which we received notification of your withdrawal from this contract. We will use the same payment method for this refund as you used for the original transaction, unless expressly agreed otherwise with you; under no circumstances will you be charged for this refund.<br /></p><p>For contracts for the supply of goods, we may refuse to refund you until we have received the goods back or until you have provided proof that you have returned the goods, whichever occurs earlier.<br /></p><p>You must return or hand over the goods to us immediately and in any case no later than fourteen days from the day on which you notify us of your withdrawal from this contract. The deadline will be met if you send the goods before the end of the fourteen-day period.<br /></p><p>We will cover the cost of returning the goods.<br />You will only have to pay for any loss in value of the goods if this is due to any handling of the goods that is not necessary in order to test the quality, characteristics and functioning of the goods.</p>
                <p>3.1.3 Exclusion or premature expiry of the right of withdrawal</p>
                <p>The right of withdrawal does not apply to contracts for the delivery of goods that are not prefabricated and whose manufacture is based on a custom selection or specification by the consumer or that are clearly tailored to the consumer’s personal needs.<br /></p><p>The right of withdrawal does not apply to contracts for the delivery of newspapers, periodicals or magazines, with the exception of subscription contracts.<br /></p><p>The right of withdrawal will expire prematurely for contracts for the delivery of sealed goods which are not suitable for return for reasons of health protection or hygiene if their seal has been removed after delivery.<br /></p><p>The right of withdrawal will expire prematurely for contracts for the delivery of sound or video recordings or computer software in a sealed package if the seal has been removed after delivery.</p>
                <h2 className="text-lg font-semibold">§ 4 Prices and terms of payment</h2>
                <p>4.1 Unless otherwise stated in the Seller’s product description, the prices quoted are total prices which include statutory VAT. Any additional delivery and shipping costs will be indicated separately in the respective product description.</p>
                <p>4.2 In individual cases, deliveries to countries outside the European Union may incur further costs for which the Seller is not responsible and which are to be borne by the Customer. These include, for example, costs for the transfer of money by credit institutions (e.g. transfer fees, exchange rate fees) or import duties or taxes (e.g. customs duties). Such costs may also be incurred in relation to the transfer of money if the delivery is not made to a country outside the European Union but the Customer makes the payment from a country outside the European Union.</p>
                <p>4.3 If prepayment by bank transfer has been agreed, payment is due immediately after conclusion of the contract, unless the parties have agreed on a later due date.</p>
                <p>4.4 The deduction of a discount is only permissible if expressly agreed in writing.</p>
                <h2 className="text-lg font-semibold">§ 5 Delivery and shipping conditions</h2>
                <p>5.1 The delivery of goods will be made by dispatch to the delivery address specified by the Customer, unless otherwise agreed. The delivery address specified in the Seller’s order processing is authoritative in the processing of the transaction.</p>
                <p>5.2 In the case of goods delivered by forwarding agent, delivery shall be free to kerbside, i.e. to the nearest public kerbside to the delivery address, unless otherwise stated in the shipping information in the Seller’s online shop and unless otherwise agreed.</p>
                <p>5.3 If the transport company returns the dispatched goods to the Seller because delivery to the Customer was not possible, the Customer shall bear the cost of the unsuccessful dispatch. This does not apply if the Customer is not responsible for the circumstance that led to the inability to deliver or if the Customer was temporarily prevented from accepting the service offered, unless the Seller had given the Customer reasonable advance notice of the service. Furthermore, this does not apply with regard to the cost of the return if the Customer effectively exercises his or her right of withdrawal. If the Customer effectively exercises his or her right of withdrawal, the cost of returning the goods is governed by the provisions set out in the Seller’s cancellation policy.</p>
                <p>5.4 The purchaser must inspect the goods for transport damage immediately after delivery and report any damage so that claims can be made to the transport insurance company and replacement deliveries arranged. The purchaser’s warranty rights under Sections 434 et seq. BGB are not restricted in the event of a breach of this obligation; in individual cases, however, the breach of obligation may give rise to contributory negligence on the part of the purchaser pursuant to Section 254 BGB.</p>
                <p>5.5 If the Customer is an entrepreneur (Section 14 BGB), delivery is always made at the Customer’s risk. This also applies to partial deliveries. If the Customer is a consumer within the meaning of Section 13 BGB, the risk of accidental loss and accidental deterioration of the sold item shall not pass to the Customer until the item is handed over, even in the case of a sale by dispatch. Delivery will be deemed to have taken place if the buyer delays acceptance.</p>
                <h2 className="text-lg font-semibold">§ 6 Reservation of title</h2>
                <p>6.1 We will retain ownership of the delivered item until full payment of the purchase price arising from the delivery contract with consumers pursuant to Section 13 BGB. If the buyer is a merchant within the meaning of the German Commercial Code (HGB), the delivered goods will remain the property of Sound Service GmbH until full payment of all claims existing against this buyer, including all ancillary claims.</p>
                <p>6.2 For the duration of the reservation of title, the purchaser is not entitled to resell, rent, lend or give away the purchased item.</p>
                <p>§ 7 Liability for defects (warranty)</p>
                <p>7.1 If the purchased item is defective, the statutory regulations regarding liability for defects apply.</p>
                <p>7.2 Notwithstanding the above, the limitation period for claims for defects in used goods is one year from delivery of the goods to the Customer. However, the reduction of the limitation period to one year does not apply</p>
                <ul>
                    <li>to items which have been used in keeping with their customary use in a building structure and have caused the building structure to be defective,</li>
                    <li>to claims for damages and reimbursement of expenses by the Customer, and</li>
                    <li>in the event that the Seller has fraudulently concealed the defect.</li>
                </ul>
                <p>If the Customer is an entrepreneur, the warranty period for new items is one year and for used items six months from the transfer of risk.</p>
                <p>7.3 The Customer is requested to lodge a complaint with the delivery company with regard to goods delivered with obvious transport damage and to inform the Seller of this. If the Customer does not comply with this, it shall have no effect on his or her statutory or contractual claims for defects.</p>
                <p>7.4 Defects or damage caused by negligent or improper handling or improper installation as well as the use of unsuitable accessories or modifications to the original parts by the Customer are excluded from the warranty.</p>
                <p>7.5 The warranty also excludes the usual and product-typical wear and tear of expendable parts such as strings, drumheads, cymbals, sticks, pots, faders, lamps, spotlight LEDs, batteries, laser diodes, pitch benders, keyboards, switches, all tubes (including built-in), reeds of harmonicas, melodicas and accordions, etc., if the defect is caused by this use-related wear and tear.</p>
                <p>7.6 There is no entitlement to loan equipment during the repair period.</p>
                <p>7.7 If the Customer accepts the goods or the ordered item despite being aware of a defect, he or she shall only be entitled to warranty claims to the extent described below if he or she expressly reserves the right to do so in text form (e.g. email) immediately after receipt of the goods.</p>
                <p>7.8 The Customer is only entitled to warranty claims due to existing transport damage if he or she has complied with his or her obligation to inspect and notify in accordance with § 2 number 4. This does not apply if the Customer is a consumer.</p>
                <h2 className="text-lg font-semibold">§ 8 Special conditions for assembly/installation services</h2>
                <p>If, according to the content of the contract, the Seller is responsible not only for the delivery of the goods but also for their assembly or installation at the Customer’s premises and, if applicable, for the corresponding preparatory measures (e.g. measurement), the following applies:</p>
                <p>8.1 The Seller will, at its discretion, provide its services either in person or by qualified personnel selected by the Seller. In doing so, the Seller may also make use of the services of third parties (subcontractors) acting on its behalf. Unless otherwise stated in the Seller’s service description, the Customer is not entitled to select a specific person to perform the requested service.</p>
                <p>8.2 The Customer must provide the Seller with the full and truthful information required for the provision of the service owed, provided that its procurement does not fall within the Seller’s scope of obligations according to the content of the contract.</p>
                <p>8.3 The Seller will contact the Customer after the conclusion of the contract in order to agree on a date for the performance owed. The Customer must ensure that the Seller or the personnel appointed by the Seller have access to the Customer’s relevant facilities at the agreed time.</p>
                <h2 className="text-lg font-semibold">§ 9 Special conditions for repair services</h2>
                <p>If, according to the content of the contract, the Seller is obliged to repair an item belonging to the Customer, the following applies:</p>
                <p>9.1 Repair services will be provided at the Seller’s registered office.</p>
                <p>9.2 The Seller will, at its discretion, provide its services either in person or by qualified personnel selected by the Seller. In doing so, the Seller may also make use of the services of third parties (subcontractors) acting on its behalf. Unless otherwise stated in the Seller’s service description, the Customer is not entitled to select a specific person to perform the requested service.</p>
                <p>9.3 The Customer must provide the Seller with all information required for the repair of the item, provided that its procurement does not fall within the Seller’s scope of obligations according to the content of the contract. In particular, the Customer must provide the Seller with a comprehensive description of the defect and inform the Seller of all circumstances that may have caused the defect identified.</p>
                <p>9.4 Unless otherwise agreed, the Customer must ship the item to be repaired to the Seller’s registered office at his or her own expense and risk. The Seller recommends that the Customer takes out transport insurance for this purpose. Furthermore, the Seller recommends that the Customer ship the item in suitable transport packaging to reduce the risk of transport damage and to conceal the contents of the packaging. The Seller shall inform the Customer immediately of any obvious transport damage so that the Customer can assert any rights it may have against the carrier.</p>
                <p>9.5 The return of the item shall be at the Customer’s expense. The risk of accidental loss and accidental deterioration of the item passes to the Customer when the item is handed over to a suitable transport person at the Seller’s registered office. At the Customer’s request, the Seller will take out transport insurance for the item.</p>
                <p>9.6 The Customer may also bring the item to be repaired to the Seller’s place of business and collect it again from there in person if this ensues from the Seller’s service description or if the parties have reached an agreement to this effect. In this case, the aforementioned provisions on liability for costs and risks when dispatching and returning the item apply accordingly.</p>
                <p>9.7 The aforementioned provisions do not limit the Customer’s statutory rights in respect of defects in the event of the purchase of goods from the Seller.</p>
                <p>9.8 The Seller shall be liable for defects in the repair service provided in accordance with statutory regulations regarding liability for defects.</p>
                <p>9.9 If the Customer does not collect the item to be repaired or the repaired item despite several reminders (request to collect and two unsuccessful reminders) or if the invoice is not paid, we are entitled to take the item into our inventory after the storage period of three months from the request to collect has expired. If the device is not collected within two weeks after the collection request or the invoice is not paid, Sound Service reserves the right to charge EUR 6.00 per week for storage costs during the storage period. After the end of four weeks after the first collection request, Sound Service is only liable for damage and loss of the device in the event of gross negligence.</p>
                <p>9.10. If the Customer has not confirmed a cost estimate within 14 days or rejects the cost estimate, we will return the device sent in advance and invoice the expenditure incurred for the defect analysis as well as the transport costs in the form of a handling fee. The handling fee is also due if the Customer arranges for us to dispose of the device. Deviations/exceptions from this must be agreed in advance.</p>
                <h2 className="text-lg font-semibold">§ 10 Redemption of promotional vouchers</h2>
                <p>10.1 Vouchers issued free of charge by the Seller as part of promotions with a specific period of validity which cannot be purchased by the Customer (hereinafter referred to as “Promotional Vouchers”) may be redeemed in the Seller’s online shop only during the specified period, unless otherwise stated on the individual Promotional Voucher and unless otherwise agreed.</p>
                <p>10.2 Individual products may be excluded from the voucher promotion if the Promotional Voucher contains a corresponding restriction.</p>
                <p>10.3 Promotional Vouchers can only be redeemed before the order process is completed. It is not possible to offset the amount retrospectively.</p>
                <p>10.4 Several Promotional Vouchers can also be redeemed for one order.</p>
                <p>10.5 The value of the goods must be at least equal to the amount of the Promotional Voucher. The Seller will not refund any remaining credit.</p>
                <p>10.6 If the value of the Promotional Voucher is not sufficient to cover the order cost, one of the other payment methods offered by the Seller may be chosen to settle the difference.</p>
                <p>10.7 The credit balance of a Promotional Voucher will not be paid out in cash nor will it earn interest.</p>
                <p>10.8 The Promotional Voucher will not be refunded if the Customer returns the goods paid for in full or in part with the Promotional Voucher as part of his or her statutory right of withdrawal.</p>
                <p>10.9 The Promotional Voucher is transferable. The Seller can discharge its obligation by rendering payment or service to the respective holder redeeming the Promotional Voucher. This does not apply if the Seller is aware or negligently unaware of the ineligibility, legal incapacity or lack of power of representation of the respective holder.</p>
                <h2 className="text-lg font-semibold">§ 11 Liability for damages</h2>
                <p>11.1 We will be liable for grossly negligent and/or intentional breaches of duty and for physical injuries caused by simple negligence.</p>
                <p>11.2 In the event of slight negligence, we will only be liable in the event of a breach of material contractual obligations, and this will be limited to the damage foreseeable at the time of conclusion of the contract. This limitation does not apply in the event of injury to life, limb or health. We will not be liable for any other damage caused by slight negligence due to a defect in the purchased object. Any liability for pre-contractual fault (culpa in contrahendo) or under the German Product Liability Act remains unaffected.</p>
                <p>11.3 Irrespective of any fault on our part, we will only be liable in the event of fraudulent concealment of a defect or arising from the assumption of a guarantee or warranty. A manufacturer’s warranty is a warranty given by the manufacturer and does not constitute our granting of a warranty.</p>
                <p>11.4 We are also responsible if the delivery becomes impossible by chance during the delay, unless the damage would also have occurred if the delivery had been made on time.</p>
                <h2 className="text-lg font-semibold">§ 12 Documents provided</h2>
                <p>12.1 If documents made available to the purchaser are protected by copyright or if the documents contain confidential information, we reserve all rights to these documents, in particular ownership. These documents may not be reproduced, distributed or otherwise made available to third parties without our express consent.</p>
                <p>12.2 If a contract is not concluded between us and the purchaser, the purchaser must return these documents to us.</p>
                <h2 className="text-lg font-semibold">§ 13 Applicable law</h2>
                <p>All legal relations between the parties shall be governed by the law of the Federal Republic of Germany, with the exclusion of laws concerning the international sale of movable goods. This choice of law applies to consumers only insofar as the protection granted is not withdrawn by mandatory provisions of the law of the state in which the consumer is ordinarily resident.</p>
                <h2 className="text-lg font-semibold">§ 14 Place of jurisdiction</h2>
                <p>If the Customer is a merchant, a legal entity under public law or a special fund under public law located within the territory of the Federal Republic of Germany, the exclusive place of jurisdiction for all disputes arising from this contract is the registered office of the Seller. If the Customer is located outside the territory of the Federal Republic of Germany, the Seller’s registered office will be the exclusive place of jurisdiction for all disputes arising from this contract if the contract or claims arising from the contract can be attributed to the Customer’s professional or commercial activity. In the aforementioned cases, however, the Seller is always entitled to bring the matter before the court at the Customer’s location.</p>
                <h2 className="text-lg font-semibold">§ 15 Alternative dispute resolution</h2>
                <p>15.1 The EU Commission provides a platform for online dispute resolution under the following link: <a href="https://ec.europa.eu/consumers/odr" target="_blank">https://ec.europa.eu/consumers/odr</a><br />This platform serves as a contact point for out-of-court settlement of disputes arising from online purchase or service contracts involving a consumer.</p>
                <p>15.2 The Seller is neither obligated nor willing to participate in dispute settlement proceedings before a consumer arbitration board.</p>
                <p className="font-mono mt-6">Version dated: 15/06/2022</p>
            </div>

        </div>

    )
}

